name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - id: install-deps
        name: Install dependencies
        run: bun install

      - id: check
        name: Run check
        run: bun run check

      - id: typecheck
        name: Run typecheck
        run: bun run typecheck

      - id: test
        name: Run test
        run: bun run test
